FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir langchain langchain-community langchain-core langchain-openai

COPY ./ai_research /app/ai_research
COPY ./core /app/core
COPY ./config /app/config

EXPOSE 5000

CMD ["python", "ai_research/intel_server.py"]
